#ifndef BOOT_USER_ADDRESS_LIMIT_H
#define BOOT_USER_ADDRESS_LIMIT_H

#define BOOT_USER_APP_FLASH_START  0x082000UL
#define BOOT_USER_APP_FLASH_END_EXCLUSIVE   0x0C0000UL
#define BOOT_USER_ALLOWED_ERASE_MASK 0x00003FFEUL

#endif
