#include "boot_user_action.h"

#include "F28x_Project.h"
#include "boot_protocol.h"
#include "boot_ram_port.h"
#include "boot_user_app_layout.h"
#include "boot_user_io_sci.h"

/*
 * Fixed-entry mode is intended only for bring-up or a known fixed-entry test app.
 * GUI / MVP delivery mode should keep BOOT_USER_FIXED_APP_ENTRY_ENABLE = 0U.
 */
#define BOOT_USER_FIXED_APP_ENTRY_ENABLE  0U
#define BOOT_USER_FIXED_APP_ENTRY         BOOT_USER_APP_START

volatile uint32_t g_boot_user_jump_entry = 0UL;

extern void BootUser_JumpToEntryAsm(void);

static uint16_t BootUser_IsValidFlashAppEntry(uint32_t entry_point)
{
    if (entry_point < BOOT_USER_APP_START)
    {
        return 0U;
    }
    if (entry_point >= BOOT_USER_APP_END_EXCLUSIVE)
    {
        return 0U;
    }
    if ((entry_point & 0x7UL) != 0UL)
    {
        return 0U;
    }
    return 1U;
}

static void BootUser_PrepareForAppJump(void)
{
    /*
     * RUN OK response must already have been generated by bootloader_core.
     * Wait until SCI TX is fully completed before branching to the app.
     *
     * Do not add distributed timeout handling here.
     * Future timeout recovery will be handled by the unified watchdog policy.
     */
    BootSci_Flush();

    DINT;

    IER = 0x0000U;
    IFR = 0x0000U;

    /*
     * If PIE is initialized/enabled in the future, clear/disable PIE state here.
     * Keep this user-layer only.
     */
}

void BootUser_JumpToFlashApp(uint32_t entry_point)
{
#if BOOT_USER_FIXED_APP_ENTRY_ENABLE
    entry_point = BOOT_USER_FIXED_APP_ENTRY;
#endif

    if (BootUser_IsValidFlashAppEntry(entry_point) == 0U)
    {
        /*
         * Safe stop for now.
         * Future behavior will be integrated with metadata/watchdog recovery.
         */
        for (;;)
        {
        }
    }

    g_boot_user_jump_entry = entry_point;
    BootUser_PrepareForAppJump();
    BootUser_JumpToEntryAsm();

    for (;;)
    {
    }
}

#if BOOT_ENABLE_RUN_RAM
void BootUser_JumpToRamApp(uint32_t entry_point)
{
    BootRamErrorInfo error_info = {0U, 0UL, 0UL, 0UL};

    if (BootRam_CheckAddress(entry_point, 1UL, BOOT_TARGET_RAM_APP, &error_info) !=
        BOOT_RAM_RESULT_OK)
    {
        for (;;)
        {
        }
    }

    g_boot_user_jump_entry = entry_point;
    BootUser_PrepareForAppJump();
    BootUser_JumpToEntryAsm();

    for (;;)
    {
    }
}
#endif

uint16_t BootUser_HandleAlgorithmAction(BootAlgorithm *algorithm,
                                        BootAlgorithmAction action)
{
    switch (action)
    {
        case BOOT_ALGORITHM_ACTION_RUN_FLASH_APP:
            BootUser_JumpToFlashApp(BootAlgorithm_GetPendingEntryPoint(algorithm));
            return 1U;

#if BOOT_ENABLE_RUN_RAM
        case BOOT_ALGORITHM_ACTION_RUN_RAM_APP:
            BootUser_JumpToRamApp(BootAlgorithm_GetPendingEntryPoint(algorithm));
            return 1U;
#endif

#if BOOT_ENABLE_RESET_COMMAND
        case BOOT_ALGORITHM_ACTION_RESET_DEVICE:
            BootUser_ResetDevicePlaceholder();
            return 1U;
#endif

        case BOOT_ALGORITHM_ACTION_NONE:
        default:
            return 0U;
    }
}

#if BOOT_ENABLE_RESET_COMMAND
void BootUser_ResetDevicePlaceholder(void)
{
    /*
     * RESET is not an enabled production feature yet.
     * DeviceInfo must not advertise RESET capability until this is implemented.
     */
    for (;;)
    {
    }
}
#endif
