#ifndef BOOT_USER_FEATURE_CONFIG_H
#define BOOT_USER_FEATURE_CONFIG_H

#ifndef BOOT_ENABLE_RUN_RAM
#define BOOT_ENABLE_RUN_RAM 0U
#endif

#ifndef BOOT_ENABLE_RESET_COMMAND
#define BOOT_ENABLE_RESET_COMMAND 0U
#endif

#ifndef BOOT_ENABLE_FLASH_READ
#define BOOT_ENABLE_FLASH_READ 1U
#endif

#ifndef BOOT_ENABLE_METADATA_SUMMARY
#define BOOT_ENABLE_METADATA_SUMMARY 1U
#endif

#endif
