"""Public PC operation library API."""

from .context import FlashOperationContext, OperationContext, ProgressCallback
from .discovery import DiscoveredTarget, TargetDiscoveryOutcome, discover_connected_target
from .execution_ops import (
    BootCpu2ResetCpu1Request,
    BootCpu2RunCpu1Request,
    ResetTargetRequest,
    RunFlashAppRequest,
    RunRamImageRequest,
    boot_cpu2_reset_cpu1,
    boot_cpu2_run_cpu1,
    reset_target,
    run_flash_app,
    run_ram_image,
)
from .flash_ops import (
    EraseFlashImageAreaRequest,
    EraseSectorMaskRequest,
    ProgramFlashImageRequest,
    VerifyFlashImageRequest,
    erase_flash_image_area,
    erase_sector_mask,
    program_flash_image,
    verify_flash_image,
)
from .metadata_ops import (
    AppendAppConfirmedRequest,
    AppendBootAttemptRequest,
    AppendImageValidRequest,
    append_app_confirmed,
    append_boot_attempt,
    append_image_valid,
)
from .memory_ops import MemoryReadRequest, memory_read
from .ram_ops import CheckRamCrcRequest, LoadRamImageRequest, check_ram_crc, load_ram_image
from .results import (
    ErrorDomain,
    OperationCancellationInfo,
    OperationCompletion,
    OperationErrorInfo,
    OperationResult,
    ProgressEvent,
    classify_exception_domain,
    operation_result_to_dict,
)
from .service_ops import attach_flash_service, get_service_status
from .status_ops import get_device_info, get_last_error, get_metadata_summary, get_protocol_info

__all__ = [
    "AppendAppConfirmedRequest",
    "AppendBootAttemptRequest",
    "AppendImageValidRequest",
    "BootCpu2ResetCpu1Request",
    "BootCpu2RunCpu1Request",
    "CheckRamCrcRequest",
    "ErrorDomain",
    "DiscoveredTarget",
    "EraseFlashImageAreaRequest",
    "EraseSectorMaskRequest",
    "FlashOperationContext",
    "LoadRamImageRequest",
    "MemoryReadRequest",
    "OperationContext",
    "OperationCancellationInfo",
    "OperationCompletion",
    "OperationErrorInfo",
    "OperationResult",
    "ProgramFlashImageRequest",
    "ProgressCallback",
    "ProgressEvent",
    "ResetTargetRequest",
    "RunFlashAppRequest",
    "RunRamImageRequest",
    "VerifyFlashImageRequest",
    "append_app_confirmed",
    "append_boot_attempt",
    "append_image_valid",
    "attach_flash_service",
    "boot_cpu2_reset_cpu1",
    "boot_cpu2_run_cpu1",
    "check_ram_crc",
    "erase_flash_image_area",
    "erase_sector_mask",
    "get_device_info",
    "get_last_error",
    "get_metadata_summary",
    "get_protocol_info",
    "get_service_status",
    "load_ram_image",
    "memory_read",
    "operation_result_to_dict",
    "program_flash_image",
    "reset_target",
    "run_flash_app",
    "run_ram_image",
    "verify_flash_image",
    "classify_exception_domain",
    "TargetDiscoveryOutcome",
    "discover_connected_target",
]
