"""Frozen logical-pixel metrics for the approved Phase 11 GUI V1.0 layout.

Qt sizes in this module are logical pixels.  Callers must not multiply these
values by a device-pixel ratio.  Colors and typography belong in the theme
modules, not here.
"""

from __future__ import annotations

from typing import Final

WINDOW_TITLE: Final = "DSP28377D Bootloader Upgrade Tool"
WINDOW_DEFAULT_SIZE: Final = (1440, 900)
WINDOW_MINIMUM_SIZE: Final = (1180, 680)

RIBBON_TOTAL_HEIGHT: Final = 130
RIBBON_TAB_ROW_HEIGHT: Final = 34
RIBBON_CONTENT_ROW_HEIGHT: Final = 96
RIBBON_LARGE_BUTTON_HEIGHT: Final = 68
RIBBON_TRANSPORT_TABS_HEIGHT: Final = 54
RIBBON_TRANSPORT_TAB_HEIGHT: Final = 22
RIBBON_TRANSPORT_FIELD_HEIGHT: Final = 30

NAVIGATION_DEFAULT_WIDTH: Final = 224
NAVIGATION_MINIMUM_WIDTH: Final = 208
NAVIGATION_MAXIMUM_WIDTH: Final = 260
PAGE_CONTENT_MINIMUM_WIDTH: Final = 720

WORKSPACE_SPLITTER_HANDLE_WIDTH: Final = 5
MAIN_AREA_SPLITTER_HANDLE_WIDTH: Final = 4
MAIN_AREA_MINIMUM_HEIGHT: Final = 360

CONSOLE_DEFAULT_EXPANDED_HEIGHT: Final = 160
CONSOLE_MINIMUM_EXPANDED_HEIGHT: Final = 120
CONSOLE_COLLAPSED_HEIGHT: Final = 34
CONSOLE_HEADER_HEIGHT: Final = 34
CONSOLE_TOOL_BUTTON_SIZE: Final = (30, 30)
CONSOLE_ICON_SIZE: Final = 16
CONSOLE_START_COLLAPSED_WINDOW_HEIGHT: Final = 760

PAGE_MARGINS: Final = (16, 14, 16, 14)
PAGE_BLOCK_SPACING: Final = 12
PAGE_TITLE_ROW_HEIGHT: Final = 36
INPUT_MINIMUM_HEIGHT: Final = 30
CARD_RADIUS: Final = 6
CONTROL_RADIUS: Final = 4

PROGRAM_CONTENT_MAXIMUM_WIDTH: Final = 1480
PROGRAM_SPLITTER_HANDLE_WIDTH: Final = 6
PROGRAM_SPLITTER_INITIAL_SIZES: Final = (58, 42)
PROGRAM_WORKFLOW_MINIMUM_WIDTH: Final = 520
PROGRAM_WORKFLOW_PREFERRED_RANGE: Final = (640, 720)
PROGRAM_WORKFLOW_MAXIMUM_WIDTH: Final = 880
PROGRAM_STATE_MINIMUM_WIDTH: Final = 360
PROGRAM_STATE_PREFERRED_RANGE: Final = (440, 560)
PROGRAM_STATE_MAXIMUM_WIDTH: Final = 640
PROGRAM_IMAGE_CARD_MINIMUM_HEIGHT: Final = 214
PROGRAM_IMAGE_ROW_HEIGHT: Final = 34
PROGRAM_OPTIONS_CARD_MINIMUM_HEIGHT: Final = 82
PROGRAM_STATUS_CARD_MINIMUM_HEIGHT: Final = 330
PROGRAM_STATUS_ROW_HEIGHT: Final = 30
PROGRAM_RESULT_CARD_MINIMUM_HEIGHT: Final = 150

SETTINGS_CONTENT_MAXIMUM_WIDTH: Final = 1360
SETTINGS_SCOPE_TAB_HEIGHT: Final = 38
SETTINGS_SCOPE_TAB_MINIMUM_WIDTH: Final = 170
SETTINGS_SPLITTER_HANDLE_WIDTH: Final = 5
SETTINGS_CATEGORY_DEFAULT_WIDTH: Final = 208
SETTINGS_CATEGORY_MINIMUM_WIDTH: Final = 184
SETTINGS_CATEGORY_MAXIMUM_WIDTH: Final = 232
SETTINGS_CATEGORY_ITEM_HEIGHT: Final = 36
SETTINGS_CONTENT_MINIMUM_WIDTH: Final = 620
SETTINGS_HEADER_MINIMUM_HEIGHT: Final = 58
SETTINGS_SECTION_GAP: Final = 12
SETTINGS_SECTION_HEADER_HEIGHT: Final = 32
SETTINGS_SECTION_BODY_MARGIN: Final = 12
SETTINGS_FORM_ROW_MINIMUM_HEIGHT: Final = 38
SETTINGS_FORM_LABEL_WIDTH: Final = 180
SETTINGS_BROWSE_BUTTON_SIZE: Final = (38, 32)
SETTINGS_ACTION_BAR_HEIGHT: Final = 52
SETTINGS_ACTION_BUTTON_MINIMUM_SIZE: Final = (96, 32)

ADVANCED_CONTENT_MAXIMUM_WIDTH: Final = 1480
ADVANCED_SPLITTER_HANDLE_WIDTH: Final = 6
ADVANCED_SPLITTER_INITIAL_SIZES: Final = (68, 32)
ADVANCED_TABS_MINIMUM_HEIGHT: Final = 260
ADVANCED_RESULT_MINIMUM_HEIGHT: Final = 130
ADVANCED_TAB_BAR_HEIGHT: Final = 38
ADVANCED_TAB_MINIMUM_WIDTH: Final = 118
ADVANCED_TAB_ICON_SIZE: Final = 16
ADVANCED_CARD_HEADER_HEIGHT: Final = 32
ADVANCED_CARD_BODY_MARGIN: Final = 12
ADVANCED_FIELD_HEIGHT: Final = 32
ADVANCED_FIELD_LABEL_WIDTH: Final = 170
ADVANCED_BUTTON_HEIGHT: Final = 34
ADVANCED_BUTTON_ICON_SIZE: Final = 16
ADVANCED_PROGRESS_STRIP_HEIGHT: Final = 54
ADVANCED_PROGRESS_BAR_HEIGHT: Final = 10

MEMORY_CONTENT_MAXIMUM_WIDTH: Final = 1480
MEMORY_CONTROL_CARD_HEIGHT: Final = 72
MEMORY_FIELD_HEIGHT: Final = 32
MEMORY_ADDRESS_WIDTH: Final = 150
MEMORY_WORD_COUNT_WIDTH: Final = 110
MEMORY_DISPLAY_FORMAT_WIDTH: Final = 130
MEMORY_SEARCH_MINIMUM_WIDTH: Final = 180
MEMORY_SPLITTER_HANDLE_WIDTH: Final = 6
MEMORY_SPLITTER_INITIAL_SIZES: Final = (90, 10)
MEMORY_TABLE_MINIMUM_WIDTH: Final = 600
MEMORY_DETAILS_MINIMUM_WIDTH: Final = 0
MEMORY_WORD_COLUMNS: Final = 16
MEMORY_TABLE_HEADER_HEIGHT: Final = 32
MEMORY_TABLE_ROW_HEIGHT: Final = 26
MEMORY_ADDRESS_COLUMN_WIDTH: Final = 92
MEMORY_WORD_COLUMN_MINIMUM_WIDTH: Final = 58

LOGS_CONTENT_MAXIMUM_WIDTH: Final = 1600
LOGS_FILTER_BAR_HEIGHT: Final = 48
LOGS_FILTER_CONTROL_HEIGHT: Final = 32
LOGS_SPLITTER_HANDLE_WIDTH: Final = 6
LOGS_SPLITTER_INITIAL_SIZES: Final = (70, 30)
LOGS_TABLE_MINIMUM_WIDTH: Final = 620
LOGS_DETAILS_MINIMUM_WIDTH: Final = 300
LOGS_TABLE_HEADER_HEIGHT: Final = 32
LOGS_TABLE_ROW_HEIGHT: Final = 28
LOGS_COLUMN_WIDTHS: Final = {
    "time": 116,
    "level": 82,
    "source": 104,
    "operation": 150,
}

DEFAULT_ICON_SIZE: Final = 16
RIBBON_ICON_SIZE: Final = 24
