"""Compatibility aliases for the retired Phase 11 static-skeleton metrics.

Runtime styling is owned by ``theme.py`` and ``resources/styles/theme.qss``.
This module intentionally contains no QSS source and no ``APP_QSS`` value.
New code must import metric names directly from ``layout_metrics.py``.
"""

from __future__ import annotations

from .layout_metrics import (
    CONSOLE_COLLAPSED_HEIGHT,
    CONSOLE_DEFAULT_EXPANDED_HEIGHT,
    MEMORY_WORD_COLUMNS,
    NAVIGATION_DEFAULT_WIDTH,
    NAVIGATION_MAXIMUM_WIDTH,
    NAVIGATION_MINIMUM_WIDTH,
    RIBBON_CONTENT_ROW_HEIGHT,
    RIBBON_TAB_ROW_HEIGHT,
    RIBBON_TOTAL_HEIGHT,
    WINDOW_DEFAULT_SIZE,
    WINDOW_MINIMUM_SIZE,
    WINDOW_TITLE,
)

# Temporary aliases retained for callers that still use the old metric names.
TITLE_TAB_ROW_HEIGHT = RIBBON_TAB_ROW_HEIGHT
TOP_RIBBON_TOTAL_HEIGHT = RIBBON_TOTAL_HEIGHT
NAVIGATION_WIDTH = NAVIGATION_DEFAULT_WIDTH
NAVIGATION_MIN_WIDTH = NAVIGATION_MINIMUM_WIDTH
NAVIGATION_MAX_WIDTH = NAVIGATION_MAXIMUM_WIDTH
BOTTOM_DOCK_EXPANDED_HEIGHT = CONSOLE_DEFAULT_EXPANDED_HEIGHT
BOTTOM_DOCK_COLLAPSED_HEIGHT = CONSOLE_COLLAPSED_HEIGHT

__all__ = [
    "BOTTOM_DOCK_COLLAPSED_HEIGHT",
    "BOTTOM_DOCK_EXPANDED_HEIGHT",
    "MEMORY_WORD_COLUMNS",
    "NAVIGATION_MAX_WIDTH",
    "NAVIGATION_MIN_WIDTH",
    "NAVIGATION_WIDTH",
    "RIBBON_CONTENT_ROW_HEIGHT",
    "TITLE_TAB_ROW_HEIGHT",
    "TOP_RIBBON_TOTAL_HEIGHT",
    "WINDOW_DEFAULT_SIZE",
    "WINDOW_MINIMUM_SIZE",
    "WINDOW_TITLE",
]
